{application,webtest,
             [{description,"An OTP application"},
              {vsn,"0.1.0"},
              {registered,[]},
              {mod,{webtest_app,[]}},
              {applications,[kernel,stdlib]},
              {env,[]},
              {modules,[webtest_app,webtest_sup]},
              {licenses,["Apache 2.0"]},
              {links,[]}]}.
